repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: check-yaml

- repo: https://gitlab.com/daverona/pre-commit/cpp
  rev: 0.8.0
  hooks:
  - id: cppcheck
    args: ["--platform=win64", "--language=c++", "--std=c++17", "--enable=warning", "--quiet", "--inline-suppr", "--library=googletest", "--library=tinyxml2"]
    files: \.cpp$

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v16.0.6
  hooks:
  - id: clang-format
    args: [-style=file]
    types: [c++]
- repo: https://github.com/lorenzwalthert/precommit
  rev: v0.4.2
  hooks:
    - id: style-files
      args:
        ['--ignore-start="^# styler: off$"', '--ignore-stop="^# styler: on$"']
      exclude: >
        (?x)^(
        tests/testthat/.*/.*\.R(md|nw)?|
        data-raw/.*|
        )$
      files: \.R$

    - id: lintr
      additional_dependencies:
      - r-lib/lintr
      - any::cyclocomp
      files: \.R$
      exclude: >
        (?x)^(
        inst/.*|
        man/.*|
        tests/.*|
        touchstone/.*|
        vignettes/.*|
        data-raw/.*|
        )$
    - id: roxygenize
      additional_dependencies:
      - r-lib/pkgapi
      files: \.R$

- repo: local
  hooks:

  - id: run-tests
    name: run-tests
    description: Run unit tests
    entry: R -e "devtools::test()"
    language: system
    files: \.R$
    pass_filenames: false
